### ISSUE TITLE
dynamic change colors when mode() change?

### ISSUE THREAD

**Issue by glepnir** [glepnir/galaxyline.nvim#10]
In viml easy to do that. but in lua  got some problem. also can use `InsertEnter` and `InsertLeave` to change .but that only work for normal and insert mode , so If want get different color in other modes, need improve.  Currently If trigger other window that will redraw the mode color ,condition is write a function in `highlight fg` filed to dynamic return color.

**Comment by glepnir** [comment]
solved ...

**Comment by BerkeleyTrue** [comment]
How was this solved?

**Comment by glepnir** [comment]
check the example eviline.lua
