### ISSUE TITLE
LspClient typo

### ISSUE THREAD

**Issue by lucax88x** [glepnir/galaxyline.nvim#108]
Thanks for your new feat, handful.

However there's a typo (twice)

https://github.com/glepnir/galaxyline.nvim/blob/90207f9c718d92a3dda4656f3c64dd15bb479559/lua/galaxyline/provider_lsp.lua#L15

Please make this "message" customizable (I would use an icon)

**Comment by glepnir** [comment]
I had fix typo. about custom msg.
```lua
gls.right[1] = {
  ShowLspClient = {
    provider = require('galaxyline.provider_lsp').get_lsp_client('your message here')  -- use default just 'GetLspClient'
    icon = ' LSP:',
    highlight = {colors.cyan,colors.bg,'bold'}
  }
}
```

and it works like this 
![image](https://user-images.githubusercontent.com/41671631/109753155-b1de5a80-7c1c-11eb-9b7a-62bf0ac9b97d.png)
