### ISSUE TITLE
processing FileType Autocommands for .gitignore

### ISSUE THREAD

**Issue by salkin-mada** [glepnir/galaxyline.nvim#11]
this happens when opening an `.gitignore` file.

issue with color for this filetype?

![scrn-2020-10-28-07-02-56](https://user-images.githubusercontent.com/12082586/97398708-f4e59580-18eb-11eb-941b-224c17942cc4.png)

**Comment by glepnir** [comment]
Oh..need given a unknow filetype  with a default color
