### ISSUE TITLE
show statuslines for all windows

### ISSUE THREAD

**Issue by siduck76** [glepnir/galaxyline.nvim#112]
How do I show galaxyline for all the windows? it just shows for the focused window 

![image](https://user-images.githubusercontent.com/59060246/111058478-e1ab1f00-84b4-11eb-838a-196086c82044.png)

**Comment by glepnir** [comment]
config short line.  like i said in this issue.
https://github.com/glepnir/galaxyline.nvim/issues/70

**Comment by glepnir** [comment]
and you can also check the people do in there https://github.com/glepnir/galaxyline.nvim/issues/12

**Comment by siduck76** [comment]
im confused , do I need to add it in all providers?

**Comment by siduck76** [comment]
@glepnir im confused , do I need to add the if statement in all the providers? this is my config https://github.com/siduck76/neovim-dots/blob/main/lua/statusline/lua.lua

**Comment by glepnir** [comment]
no just write in short line section.

**Comment by siduck76** [comment]
@glepnir is it possible to show the same statusline for all windows?

**Comment by glepnir** [comment]
try to set short line list to empty

**Comment by siduck76** [comment]
that does nothing : gl.short_line_list = { } , I want the statusline to be the same on all windows , like airline/lightline does

![image](https://user-images.githubusercontent.com/59060246/111777237-09491f80-88d9-11eb-9e31-3e2182b7fe04.png)

**Comment by glepnir** [comment]
hmm this will trigger the winleave autocmd. I used lightline before. it use inactive keyword .  can support it set all window both use same line. but I am consider that performance in normal file type.
![image](https://user-images.githubusercontent.com/41671631/111779671-5f29c180-88f1-11eb-92e1-5732527e75f3.png)

**Comment by glepnir** [comment]
I think I need rethinking about short line and inactive line

**Comment by glepnir** [comment]
update. should be works now. if short line list is empty . you will see same line in every window.

**Comment by siduck76** [comment]
thanks! that works very well . Btw is there any way I could make the inactive statuslines the same color? like make it look dimmed so the active statusline looks in focus 

![image](https://user-images.githubusercontent.com/59060246/111784333-516c4000-88e1-11eb-8a40-ba3487d9deb5.png)

**Comment by glepnir** [comment]
hmm support it tomarrow.

**Comment by siduck76** [comment]
Thanks I'll wait :)

**Comment by siduck76** [comment]
@glepnir how do I change the backrgound color for inactive statusline? 
![image](https://user-images.githubusercontent.com/59060246/112743096-f22dc000-8fb1-11eb-96cb-11e2f015b774.png)
