### ISSUE TITLE
Keep the same status bar for popup

### ISSUE THREAD

**Issue by tami5** [glepnir/galaxyline.nvim#113]
Hey @glepnir, Is there an option to not update status bar when for example I open popups. It's a bit inconvenient that when I open popup (like opening a telescope popup). the current status line becomes just a filetype and filename, I don't want it to refresh  Also, is there a way to keep the status line the same when having splits (like hiding some stuff) 

Thanks

**Comment by glepnir** [comment]
It can be support i think

**Comment by tami5** [comment]
> It can be support i think

Yah that would be awesome for OCD, I just get easily distracted and I like ui stuff not changing a lot.

> about this you can use condition hide according width
> 
> 
> l
> https://github.com/glepnir/galaxyline.nvim/blob/6a88f1bc181bef0ad2b10e962e30896cb064818a/lua/galaxyline/condition.lua#L27-L33


I meant more like when you have to splits open , one shows the status-line configuration and the other shows an empty status like with filename and filetype. I think this behavior is called blurring unfocused window or something
