### ISSUE TITLE
Weird spaces around mid section

### ISSUE THREAD

**Issue by diegoquiroz** [glepnir/galaxyline.nvim#114]
I'm using one of the example configs (without changes), but I'm having spacing issues. The mid section has a spacing around.

I don't know if is an OS problem. I'm happy to provide more information if needed.

<img width="1994" alt="Screen Shot 2021-03-16 at 18 48 48" src="https://user-images.githubusercontent.com/10314128/111398037-41a5ef00-8688-11eb-8c17-a9e85e29c840.png">

**Comment by glepnir** [comment]
check your colorscheme `Statusline` color.

**Comment by zcyzhou** [comment]
I used the `eviline.lua` in `example` directory and met the same issue. Any solution?
