### ISSUE TITLE
LSPs do not update in statusline when buffers with different filetypes are open

### ISSUE THREAD

**Issue by olimorris** [glepnir/galaxyline.nvim#115]
Using the custom `ShowLspClient` element from `eviline.lua`, I struggle to get it to update when I have a Python and a Lua buffer open at the same time.

If I open a Lua file I see `sumneko_lua` displayed in the status line.. Then if I open up a Python file I just see `No Active Lsp`. Conversely, I start in the python buffer then I see `pyright` and then `No active Lsp` in the Lua file. This is odd as I do see Lsp warnings in the code itself so I know the Lsp's are working.

My Galaxyline config is:

```
{
        ShowLspClient = {
            provider = 'GetLspClient',
            condition = function ()
              local tbl = {['dashboard'] = true,['']=true}
              if tbl[vim.bo.filetype] then
                return false
              end
              return true
            end,
            icon = ' LSP:',
            highlight = {color('blue'), color('bg'), 'bold'}
          }
    },
```

**Comment by glepnir** [comment]
@olimorris  had fixed. please update.
