### ISSUE TITLE
I don't see Git information

### ISSUE THREAD

**Issue by sphynx79** [glepnir/galaxyline.nvim#117]
Can you insert in documentation if this StatusLine need other plugin to see git information, because in my case i insert git provider but i don't see nothing, And i don't use git plugin for my neovim.
Another question how i get git branch with this plugin itchyny/vim-gitbranch or use this simple command 
!git rev-parse --abbrev-ref HEAD

**Comment by glepnir** [comment]
galaxyline support show git branch infomation by default provider. provide min config.
