### ISSUE TITLE
git Diff is not working

### ISSUE THREAD

**Issue by arpangreat** [glepnir/galaxyline.nvim#124]
Hii I am using nvim as prequeries and also using a updated Manjaro device .
But Unfortunately the git diff signs are not showing up... I am using the spaceline config in the examples with some tweaks.

can someone help me out ?? :blush:

**Comment by glepnir** [comment]
@arpangreat  you need install git diff plugins one of vim-gitgutter vim-signify gitsigns

**Comment by arpangreat** [comment]
Thanks for your help
