### ISSUE TITLE
hide statusline in specific windows 

### ISSUE THREAD

**Issue by siduck76** [glepnir/galaxyline.nvim#128]
Hi , Is it possible to hide galaxyline on specific windows like terminal? something like this 
![image](https://user-images.githubusercontent.com/59060246/113500392-32a1b680-953b-11eb-82a0-bfcc42b85bde.png)

**Comment by siduck76** [comment]
nevermind , I had a workaround which fixed it .

**Comment by glepnir** [comment]
hmm I think the way is set the special buffer statusline to empty and set the background color same as background color

**Comment by siduck76** [comment]
yeah I changed the StatusLineNC's bg to none and filled it with chars 
highlight! StatusLineNC gui=underline guibg=NONE guifg=#3e4451"

![image](https://user-images.githubusercontent.com/59060246/113505600-82917500-955d-11eb-976e-e89eb1422ac5.png)
