### ISSUE TITLE
Error in updating color in Visual Block mode

### ISSUE THREAD

**Issue by Tinku10** [glepnir/galaxyline.nvim#140]
#### Issue
When I try to switch to visual block mode, editor throws an error saying attempting to  concatenate a nil value.

```
Invalid expression: luaeval(require("galaxyline").component_decorator')("ViMode")
```
This is the command I am using 
```lua
vim.api.nvim_command('hi GalaxyViMode guifg='..mode_color[vim.fn.mode()])
```
Also I tried checking what the vim.fn.mode() returns. In block mode it is returning '^V'. I also tried to do a check to see if it is returning null of the string '^V' but nothing works.

**Comment by wh1tevs** [comment]
to input `^V` character you need to enter input mode and press `<c-v>` twice.

**Comment by Tinku10** [comment]
@wh1tevs
Thanks, it solved the issue. But I have a doubt. Why writing '^V' manually didn't work and doing what you told did.

**Comment by wh1tevs** [comment]
@Tinku10 because `^V` as text is a two separated symbols, but `^V` character is a special control symbol who just looks like `^V`
[`:h i_CTRL-V`](https://vimhelp.org/insert.txt.html#i_CTRL-V)
[`:h i_CTRL-V_digit`](https://vimhelp.org/insert.txt.html#i_CTRL-V_digit)
[`:h digraph-table`](https://vimhelp.org/digraph.txt.html#digraph-table)

**Comment by Tinku10** [comment]
@wh1tevs Thanks, got it.

**Comment by xeho91** [comment]
> @Tinku10 because `^V` as text is a two separated symbols, but `^V` character is a special control symbol who just looks like `^V`
> [`:h i_CTRL-V`](https://vimhelp.org/insert.txt.html#i_CTRL-V)
> [`:h i_CTRL-V_digit`](https://vimhelp.org/insert.txt.html#i_CTRL-V_digit)
> [`:h digraph-table`](https://vimhelp.org/digraph.txt.html#digraph-table)

Thank you man, I encountered the same issue, and I've been struggling over it for a while!
