### ISSUE TITLE
breaking change in colorbuddy breaks colorgroups for shell

### ISSUE THREAD

**Issue by matu3ba** [glepnir/galaxyline.nvim#147]
I have a completely freezing neovim, when I use galaxyline and open a shell document.

TJ made yesterday a breaking change: https://github.com/tjdevries/colorbuddy.nvim/commit/5d1881126b5d33af3195d3c4f86cf4107a081a9c

Took my quite a while to track down and I will make frequent backups of all plugins in future as to not have this problem again.

**Comment by wh1tevs** [comment]
How that situation correlate with this plugin?

**Comment by matu3ba** [comment]
Not sure how or why, but updating the example fixed it.
