### ISSUE TITLE
one statusline for multiple windows

### ISSUE THREAD

**Issue by siduck** [glepnir/galaxyline.nvim#169]
Is it possible to have only one window for multiple windows? rather than having multiple statuslines!

I wouldnt want this : 

![image](https://user-images.githubusercontent.com/59060246/119433138-41cf0480-bd33-11eb-9291-d79553c86e3e.png)

**Comment by sangdth** [comment]
If I remember correctly, I read somewhere on readdit that the statusline is stick with one buffer. Some people try to do the trick, like detect the far left for beginning, far right for the end, and every buffer in the middle for the space in middle, but the code is really messy and I didn't want to use it.
