### ISSUE TITLE
[Feature request] Ability to show latest git commit info/message

### ISSUE THREAD

**Issue by sangdth** [glepnir/galaxyline.nvim#171]
Hi, thanks for your awesome work. I'm trying to get the statusline showing the latest git commit information (author, date, message) I tried to find around here as well as Google but has no luck. Do you have any plan to implement it or know how to work around?

Sorry if this question already asked / duplicated.

**Comment by Unoqwy** [comment]
You can read from command `git log -1` (latest commit information).
You can extract the information you want using git [pretty formats](https://git-scm.com/docs/pretty-formats).
For example, `git log -1 --pretty="%cN, %ar, %s"` will output something like `You, 12 days ago, Some progress on feature`. Note that you most likely want to limit the number of chars. 

For the implementation itself, you can read command's output using `io.popen`. [Here](https://github.com/glepnir/galaxyline.nvim/blob/main/lua/galaxyline/provider_vcs.lua#L105-L109) is an example.

**Comment by sangdth** [comment]
Thank you, I will give it a try.

**Comment by sangdth** [comment]
I found out a way,  using the `coc-git` (I know it's not "lua-qualified" but it works for me at least for now), I can reach the `b:coc_git_blame` and assign it back to galaxyline is so smooth:
```
        provider = function()
            return vim.b.coc_git_blame or 'nothing'
        end,
```
