### ISSUE TITLE
Statusline stays in inactive mode after closing Nvim-tree

### ISSUE THREAD

**Issue by SmiteshP** [glepnir/galaxyline.nvim#172]
Galaxyline stays inactive after closing nvim-tree. But opening a new tab or writing the file brings it back to normal.
Here is an example of the bug

https://user-images.githubusercontent.com/43147494/120063418-c350ca80-c084-11eb-88da-9dcefa42d170.mp4

**Comment by SmiteshP** [comment]
My galaxyline config can be found [here](https://github.com/SmiteshP/Dotfiles/blob/master/.config/nvim/lua/config/galaxyline.lua)

**Comment by Pocco81** [comment]
I'm experiencing the same issue too. Hope @SmiteshP's PR gets merged soon!

**Comment by siduck76** [comment]
I have the same issue! :c 

![image](https://user-images.githubusercontent.com/59060246/120093244-9957e080-c136-11eb-8c40-b73760bb40df.png)

**Comment by SmiteshP** [comment]
@Pocco81 @siduck76 
Adding the following line to your init.vim can be used as a temporary fix :)
`autocmd BufHidden * lua require('galaxyline').load_galaxyline()`

**Comment by siduck76** [comment]
@SmiteshP  doesnt work :(

![image](https://user-images.githubusercontent.com/59060246/120135496-024e5f80-c1ee-11eb-9e90-476f3da8bcd6.png)

**Comment by SmiteshP** [comment]
Hey @siduck76 !
I cloned your neovim-dotfiles and tried using this. It seems to fix this issue just fine. However, looking at your screenshot it seems that the galaxyline isn't becoming inactive for you when nvim-tree is open?

https://user-images.githubusercontent.com/43147494/120138503-3cbafb00-c1f4-11eb-9f20-7e30cf7fcf44.mp4

**Comment by siduck76** [comment]
@SmiteshP yeah its weird , this wasnt happening before :(

**Comment by Pocco81** [comment]
@SmiteshP the temporary fix worked for me, thanks :)

**Comment by siduck76** [comment]
@SmiteshP are you able to disable galaxyline in NvimTree? check https://github.com/glepnir/galaxyline.nvim/issues/178
