### ISSUE TITLE
disable statusline in NvimTree

### ISSUE THREAD

**Issue by siduck76** [glepnir/galaxyline.nvim#178]
Hi there! Is it possible to disable the statusline in nvimtree? I dont think its needed and it looks bad too 

![image](https://user-images.githubusercontent.com/59060246/120410879-7c5b2180-c371-11eb-9961-a2b46517bc2b.png)

I tried this but didnt work either :

```
vim.api.nvim_exec(
    [[

function! DisableST()
  return " "
endfunction
au BufEnter NvimTree setlocal statusline=%!DisableST()

]],
    false
)  
``` 

I found some [config](https://github.com/kyazdani42/dotfiles/blob/d9a9035c6bea5b045a1f15f4055d8f84bffa157b/config/common/nvim/lua/statusline.lua#L111) but Idk how to implement it in galaxyline , doesnt work :c

**Comment by SmiteshP** [comment]
Have you tried adding this to your config
`require("galaxyline").short_line_list = { "NvimTree" }`

**Comment by siduck76** [comment]
I tried that , didnt work :(

![image](https://user-images.githubusercontent.com/59060246/120411428-6c900d00-c372-11eb-9e67-de4db4d075f2.png)

**Comment by SmiteshP** [comment]
Hmm.. I don't think that can be avoided. The best that can be done is to have short_line's background match the background of the colourscheme.

**Comment by siduck76** [comment]
@SmiteshP I did that and yes it works 

![image](https://user-images.githubusercontent.com/59060246/120415103-9d734080-c378-11eb-8ecc-fc76fe1bf6a4.png)

but this makes my StatuslineNc ugly too :(

![image](https://user-images.githubusercontent.com/59060246/120415252-dc08fb00-c378-11eb-849d-c4b82bf3a0d2.png)
\

**Comment by SmiteshP** [comment]
@siduck76 Try using this, seems to work for me
```
au BufEnter,BufWinEnter,WinEnter,CmdwinEnter *
                       \ call s:disable_statusline('NvimTree')
fun! s:disable_statusline(bn)
   if a:bn == bufname('%')
       set laststatus=0
   else
       set laststatus=2
   endif
endfunction
```
[Stackoverflow](https://stackoverflow.com/a/7150908/11114431)

**Comment by siduck76** [comment]
@SmiteshP sorry to bother! Im still new to lua and  I have a lua nvim config , could you write a lua config for it

**Comment by SmiteshP** [comment]
I would just stick it inside vim.cmd like so
```
vim.cmd [[
au BufEnter,BufWinEnter,WinEnter,CmdwinEnter *
                       \ call s:disable_statusline('NvimTree')
fun! s:disable_statusline(bn)
   if a:bn == bufname('%')
       set laststatus=0
   else
       set laststatus=2
   endif
endfunction
]]
```
There is probably a more elegant way of doing it through lua but I am new to lua as well :)

**Comment by siduck76** [comment]
I tried that and it didnt work ( I removed nvimtree from shortline )

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/120418275-d5c94d80-c37d-11eb-92b8-77b2d55ed55e.png)

![image](https://user-images.githubusercontent.com/59060246/120418287-dd88f200-c37d-11eb-9bf3-707b47b71e36.png)

**Comment by SmiteshP** [comment]
Here is how it looks for me.

https://user-images.githubusercontent.com/43147494/120418281-d95cd480-c37d-11eb-8b08-cb36526a4f9d.mp4

**Comment by siduck76** [comment]
could you open more windows and check how does  StatuslineNC ( statusline in inactive window ) look?

**Comment by SmiteshP** [comment]
It works as I would expect it to


https://user-images.githubusercontent.com/43147494/120418755-c1398500-c37e-11eb-8cec-1d9ae182e4d3.mp4

**Comment by siduck76** [comment]
yeah it works for me only if I focus on NvimTree window but if I dont then the statuslineNc shows

**Comment by SmiteshP** [comment]
Yeah! I see what your saying. But I don't know how to fix it ¯\_(ツ)_/¯

**Comment by siduck76** [comment]
@SmiteshP is it possible to disable the statusline on terminal windows?

**Comment by SmiteshP** [comment]
Found a answer on [StackExchange](https://unix.stackexchange.com/a/140899/333552)
The toggle function can easily be set to run on terminal open and close events using autocmd

```
let s:hidden_all = 0
function! ToggleHiddenAll()
    if s:hidden_all  == 0
        let s:hidden_all = 1
        set noshowmode
        set noruler
        set laststatus=0
        set noshowcmd
    else
        let s:hidden_all = 0
        set showmode
        set ruler
        set laststatus=2
        set showcmd
    endif
endfunction

autocmd TermOpen * silent! call ToggleHiddenAll()<CR>
autocmd TermLeave * silent! call ToggleHiddenAll()<CR>
```

Of course you might want to tweak the options changes inside the toggle function according to your needs.

**Comment by siduck76** [comment]
damnn this seems long af , I have tried this 

```  au BufEnter term://* set laststatus=0 ```

But it works on some term buffers (like only on the bottom)

**Comment by siduck76** [comment]
Finally I was able to disable statusline in NvimTree 

vim.api.nvim_exec(
    [[
   au BufEnter,BufWinEnter,WinEnter,CmdwinEnter * if bufname('%') == "NvimTree" | set laststatus=0 | else | set laststatus=2 | endif
]],
    false
)

add guibg to this too 

NvimTreeStatuslineNc
