### ISSUE TITLE
[FR] A way to add filetypes/icons to FileIcon provider?

### ISSUE THREAD

**Issue by madskjeldgaard** [glepnir/galaxyline.nvim#18]
Hi

A small issue I am having is that I am using some filetypes that are "rare" in most circumstances and thus not covered by the FileIcon provider. As a result I see the question mark icon a lot for those but I would love to be able to add my own icons to the provider. 

And just fyi, the file types I am talking about are for example `supercollider` (.scd and .sc).

Thanks! <3

**Comment by madskjeldgaard** [comment]
Another example is `PKGBUILD` filetype

**Comment by glepnir** [comment]
@madskjeldgaard  api
```lua
local my_icons = require('galaxyline.provider_fileino').define_file_icon()
my_icons['you file type here'] = { color code, icon}
-- if your filetype does not define in neovim  you can use file extensions ,get ext 
my_icons['your file ext  in here'] = { color code, icon}
```

**Comment by madskjeldgaard** [comment]
Thanks <3

**Comment by madskjeldgaard** [comment]
Ah, just realised I had to update to get this. amazing. It works!
