### ISSUE TITLE
Error running config for Galaxyline.nvim : [string "..."]: 0:module 'my_statusline' not found

### ISSUE THREAD

**Issue by Johan-Palacios** [glepnir/galaxyline.nvim#187]
I have this issue
![image](https://user-images.githubusercontent.com/77251405/122660431-b7fe3580-d13e-11eb-96f2-ec02f13ba08e.png)

How I can solve it?

**Comment by archaengel** [comment]
If you used the table from the README in packer, you just need to remove the config entry:
```lua
use {
  'glepnir/galaxyline.nvim',
    branch = 'main',
    -- your statusline
    config = function() require'my_statusline' end, -- remove this line
    -- some optional icons
    requires = {'kyazdani42/nvim-web-devicons', opt = true}
}
```
The error's just letting you know packer couldn't find a lua module called 'my_statusline'.
