### ISSUE TITLE
Error when launching nvim

### ISSUE THREAD

**Issue by trebaud** [glepnir/galaxyline.nvim#19]
I get this error after installing the plugin

![Screenshot from 2020-10-31 10-45-46](https://user-images.githubusercontent.com/8050949/97782167-59ac2480-1b66-11eb-8118-bc405498af08.png)

**Comment by glepnir** [comment]
@trebaud  which neovim verison that you used?

**Comment by trebaud** [comment]
Im using:

```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

**Comment by glepnir** [comment]
@trebaud  you must use neovim 0.5+ .  the lua api in neovim 0.5 version above.

**Comment by trebaud** [comment]
@glepnir  thank you :+1:

**Comment by trebaud** [comment]
@glepnir Im sorry I installed nvim 0.5 and the plugin with vim-plug, I dont get any errors anymore, but I don't get anything either in my statusline. Is there any additionnal configuration that needs to be done that is not listed in the README? I have these set in my init.vim: 
```
set termguicolors
set laststatus=2
```

Sorry I'm a bit noob when it comes to nvim and lua. Thanks!

**Comment by glepnir** [comment]
hmm. the galaxyline only provide api and default provider . then you can build your own statusline based on your ideas. You can find examples in `example` folder. it has two files that show your how to build a statusline. Also you can copy it to use.
First you can create a fold called `lua` in `~/.config/nvim`. then create a file named `myline` or something you like. then create your own statusline based on galaxyline api. or copy content of examples folder `eviline` or `spaceline`  to this file.
If you used `vim-plug`, seems like you use vim file . so you need  do like this
```vim
lua <<EOF
require('myline')
EOF
```

**Comment by trebaud** [comment]
@glepnir awesome that worked, thanks! small detail the runtime was expecting a .lua file for my statusline config file, so `myline.lua` in my case. Thanks for the awesome work!
