### ISSUE TITLE
[depracated] lsp modules uses diagnostic api that is deprecated in 0.6

### ISSUE THREAD

**Issue by kunzaatko** [glepnir/galaxyline.nvim#220]
There is a deprecation on `vim.lsp.diagnostic.{get_count,get_line_diagnostics}`. `vim.diagnostic.get` should be used instead. There is a full list of deprecations in `:h deprecated`.

**Comment by kunzaatko** [comment]
You can assign it to me, but I will have time in about 2 weeks.

**Comment by kunzaatko** [comment]
akinsho/bufferline.nvim#272

**Comment by weeman1337** [comment]
see #219

**Comment by kunzaatko** [comment]
Yeah, this works. I think this is a full fix of this issue, looking through the diff.

Closing in favour of #219
