### ISSUE TITLE
How to remove the galaxyline plugins?

### ISSUE THREAD

**Issue by sober-wang** [glepnir/galaxyline.nvim#227]
It's like topic 

My NeoVim version: v0.6.0
I'm clean the plugins in packer plugin mananger, but It's always display some problem when I open my Neovim. 
![图片](https://user-images.githubusercontent.com/35804630/150279491-0aed6e28-7dbe-4c5c-bf2f-f50abe7615b1.png)

**Comment by notwidow** [comment]
remove galaxyline file. remove from packer. remove from loading it .like somewhere in your config require(galaxyline ) or whatever you named it .. and then PackerSync...done
