### ISSUE TITLE
How to inherit colors from colorscheme?

### ISSUE THREAD

**Issue by kflak** [glepnir/galaxyline.nvim#23]
Pretty much what the title says. I can't quite figure out how to do something like this:

```
local colors = {
		bg = colorscheme.bg,
		yellow = colorscheme.yellow,
		cyan = colorscheme.cyan,
                .... etc....
}
```
Is this (easily) doable? I'm a complete lua noob, so please bear with me ;-)

K

**Comment by glepnir** [comment]
Can you explain in detail what you are going to do? colors is just a custom table variable to store some color values, which has nothing to do with galaxyline, which means you can define any color variable you want, just pass it to highlight.If you want to match your current color theme, you need to get the color code from your theme

**Comment by kflak** [comment]
Right! I looked a bit more into the details of my colorscheme, and of course things are a bit more complex than I would like :-D 

I use base16 colorschemes and change them depending on time of day and mood in general. In my base16 plugin dir there is a colors dir with a bunch of colors. The definition of colors here follows the scheme: 
```
  let g:terminal_color_0 =  "#1d2021"
  let g:terminal_color_1 =  "#d72638"
  let g:terminal_color_2 =  "#88b92d"
  let g:terminal_color_3 =  "#f19d1a"
  let g:terminal_color_4 =  "#1e8bac"
  let g:terminal_color_5 =  "#be4264"
  let g:terminal_color_6 =  "#1ba595"
  let g:terminal_color_7 =  "#d5d5d5"
  let g:terminal_color_8 =  "#6f7579"
  let g:terminal_color_9 =  "#d72638"
  let g:terminal_color_10 = "#88b92d"
  let g:terminal_color_11 = "#f19d1a"
  let g:terminal_color_12 = "#1e8bac"
  let g:terminal_color_13 = "#be4264"
  let g:terminal_color_14 = "#1ba595"
  let g:terminal_color_15 = "#e5e5e5"
  let g:terminal_color_background = g:terminal_color_0
  let g:terminal_color_foreground = g:terminal_color_5
  if &background == "light"
    let g:terminal_color_background = g:terminal_color_7
    let g:terminal_color_foreground = g:terminal_color_2
  endif
```
So, basically, what I would like to do is to access programmatically the `g:terminal_color_*` variables from my `galaxylineconf.lua` to set the color scheme. Maybe something like this: 
```
local colors = {
    bg = g:terminal_color_0,
    fg = g:terminal_color_5,
   ...etc...
}
```
Not quite sure how to do that in lua, but seems like it should be possible?

**Comment by glepnir** [comment]
you need use `vim.g.terminal_color_xxx`

**Comment by kflak** [comment]
Thanks!!!
