### ISSUE TITLE
How can I add the indentation specification ?

### ISSUE THREAD

**Issue by NikolaM-Dev** [glepnir/galaxyline.nvim#236]
Something like this...

![image](https://user-images.githubusercontent.com/62358156/189146349-2dc4b06d-f715-4876-b2c9-a07a30f1bb4b.png)

**Comment by glepnir** [comment]
return vim.opt_local.shiftwidth

**Comment by NikolaM-Dev** [comment]
But I don't know how to configure it :C

**Comment by glepnir** [comment]
```lua
provider = funciton()
  return 'Spaces: ' .. vim.bo.shiftwidth
end
```
