### ISSUE TITLE
is plugin maintained?

### ISSUE THREAD

**Issue by notwidow** [glepnir/galaxyline.nvim#237]

**Comment by glepnir** [comment]
this version maybe not， next version developing

**Comment by notwidow** [comment]
> this version maybe not， next version developing

glad to hear about the next version....
and by the way i once tried your cosynvim and it's startup time was good... but i did not checked other functions because it was giving me alot of errors... do i need some utilities for cosynvim? because i am running Arch Linux with minimal packages...

**Comment by glepnir** [comment]
no need any utilities , it's a neovim config template.

**Comment by notwidow** [comment]
> no need any utilities , it's a neovim config template.

but it was giving me errors.....

**Comment by glepnir** [comment]
you should post your error I am not god .

**Comment by notwidow** [comment]
> you should post your error I am not god .
I know ...but that was a month ago.... anyway i want your galaxyline config....
