### ISSUE TITLE
Changing colorscheme breaks the statusline theme inside neovim

### ISSUE THREAD

**Issue by Rellotscrewdriver** [glepnir/galaxyline.nvim#239]
Normally, this goes in discussions's Q&A but since there's none, I asked here.

I have configured statusline to show correctly in the default theme which I frequently use(it has some inconsistenices). 
but when changing to different colorscheme(not just catpuccin) inside neovim the element's background don't match the same.

I've tried changing the bg_color variable(which goes in every element's highlight) to 'Statusline' and 'WinBar' but both of them show the current colorscheme and not the statusline's theme. 
So how to I make the elements highlight match the current statusline theme everytime I change the colorscheme inside neovim?

here's the code: https://github.com/Rellotscrewdriver/neovim_config/blob/master/lua/statusline.lua

here's the example:
default theme
![Screenshot from 2023-04-02 10-05-08](https://user-images.githubusercontent.com/50903223/229331536-93d87080-5d85-4bc2-a455-66c8b0c8527c.png)

darkblue theme from neovim(for example of changed colorscheme)
![Screenshot from 2023-04-02 10-05-30](https://user-images.githubusercontent.com/50903223/229331533-a33a44e0-c3a6-471f-82ea-db2db2d52b7c.png)

**Comment by xiaoshihou514** [comment]
Bro u r using lualine not galaxyline
https://github.com/Rellotscrewdriver/neovim_config/blob/master/lua/plugins.lua#L30-L30

**Comment by Rellotscrewdriver** [comment]
@xiaoshihou514 I used to use galaxyline until this very issue and since it's been a month of inactivity, I had to change the plugin. Although I forgot to close this issue after that.
I will close this issue if you want to reply back ;)

**Comment by xiaoshihou514** [comment]
@Rellotscrewdriver Sorry for the misunderstanding, if you take a look at [this file](https://github.com/nvimdev/galaxyline.nvim/blob/main/lua/galaxyline/theme.lua) you can see galaxyline.theme is merely a preconfigured table of colors. If you want to adapt your colors with your colorscheme I would suggest getting colors from highlight groups(Comment, Title etc), though you would have to work out the combinations yourself :P
