### ISSUE TITLE
Path instead of just filename

### ISSUE THREAD

**Issue by bobicino** [glepnir/galaxyline.nvim#25]
Hi!
I would like to see in my bar the complete path, not just the filename. Say I am in `Documents` and open the file `Documents/folder1/file1`. I would like to see `folder1/file1`, as I had before with `lightline`. Hope it is possible. Thanks

**Comment by glepnir** [comment]
hmm it is very easy to do ，you can write a easy provider that a function renturn vim.fn.expand（%：p）

**Comment by bobicino** [comment]
Sent a pull request. Hope you can merge. Sorry I am new to git and github. Used the web interface to patch.

**Comment by glepnir** [comment]
seems like you find way to use galaxyline. so closed.
