### ISSUE TITLE
galaxyline changes other colours too

### ISSUE THREAD

**Issue by p00f** [glepnir/galaxyline.nvim#3]
![Screenshot from 2020-10-25 00-06-14](https://user-images.githubusercontent.com/36493671/97090999-234a4300-1656-11eb-8f6e-09262ee65c99.png)
Sign column - mhinz/vim-signify
bottom - liuchengxu/vim-which-key

**Comment by p00f** [comment]
(I'm using the example config)

**Comment by glepnir** [comment]
hey&nbsp; it is should be problem with your color scheme . galaxyline just provide api to build statusline.&nbsp;

--------------原始邮件--------------
发件人："Chinmay Dalal "<notifications@github.com&gt;;
发送时间：2020年10月25日(星期天) 凌晨2:39
收件人："glepnir/galaxyline.nvim" <galaxyline.nvim@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[glepnir/galaxyline.nvim] galaxyline changes other colours too (#3)
-----------------------------------

 

 

 Sign column - mhinz/vim-signify
 bottom - liuchengxu/vim-which-key

**Comment by glepnir** [comment]
you can check my colorschme Zephyr.&nbsp;

--------------原始邮件--------------
发件人："Chinmay Dalal "<notifications@github.com&gt;;
发送时间：2020年10月25日(星期天) 凌晨2:39
收件人："glepnir/galaxyline.nvim" <galaxyline.nvim@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：Re: [glepnir/galaxyline.nvim] galaxyline changes other colours too (#3)
-----------------------------------

 

 
(I'm using the example config)

**Comment by p00f** [comment]
but when i disable galaxyline this problem disappears:
![Screenshot from 2020-10-25 00-13-57](https://user-images.githubusercontent.com/36493671/97091134-24c83b00-1657-11eb-819c-1d6aad15df84.png)

**Comment by p00f** [comment]
hmm i don't have this problem with zephyr..

**Comment by glepnir** [comment]
seems like some highlight group have same name?  I will check it …when i wake up

**Comment by glepnir** [comment]
@p00f  I had a easy patch. can you test it?

**Comment by p00f** [comment]
yay it works
