### ISSUE TITLE
Show coc status in galaxyline

### ISSUE THREAD

**Issue by ludwj61** [glepnir/galaxyline.nvim#31]
Is there a way to use the ``coc#status()`` with this plugin? I know diagnostics, warnings, etc. are supported, but this function (and others like ``coc_current_function`` show more info. Is there a way to call vim plugin functions from lua?

**Comment by glepnir** [comment]
@ludwj61  like `vim.fn['coc#stats']()`

**Comment by ludwj61** [comment]
Thanks, that works. However, coc#status seems to be inserting errors/warnings when it shouldn't be (using coc#status on the default statusline doesn't have that affect). I don't think that that's this plugins fault, though.

**Comment by VickyJin** [comment]
Late to the party, but I find that `coc#status` does involve the diagnostic info now, see [here](https://github.com/neoclide/coc.nvim/blob/0480cbd9976529f69aeb692d8e1834d3edde90c5/autoload/coc.vim#L120). 
If anyone needs the separate part, try `vim.g.coc_status`.
