### ISSUE TITLE
Reappears when using Goyo on save

### ISSUE THREAD

**Issue by ChristianChiarulli** [glepnir/galaxyline.nvim#34]
Just wondering if you would consider looking into this issue.

When I save a file and Goyo is active the bar reappears. I would like it to stay hidden when Goyo is active.

![image](https://user-images.githubusercontent.com/29136904/98899748-3e061f80-247e-11eb-8993-3ac72a869df6.png)

**Comment by glepnir** [comment]
How about use
 ```
autocmd User GoyoEnter set laststatus=0 
autocmd User GoyoLeave set laststatus=2
```

**Comment by ChristianChiarulli** [comment]
tried that, didn't work for me :/

**Comment by glepnir** [comment]
update galaxyline and use this
```
autocmd! User GoyoEnter lua require('galaxyline').disable_galaxyline()
autocmd! User GoyoLeave lua require('galaxyline').galaxyline_augroup()

```

**Comment by ChristianChiarulli** [comment]
:+1: thanks

**Comment by hrqmonteiro** [comment]
> update galaxyline and use this
> 
> ```
> autocmd! User GoyoEnter lua require('galaxyline').disable_galaxyline()
> autocmd! User GoyoLeave lua require('galaxyline').galaxyline_augroup()
> ```

This is not working at all here. Galaxyline is appearing with Goyo on whether i saved the file or not.

**Comment by glepnir** [comment]
@hrqmonteiro  did it reproduce with a min config?

**Comment by hrqmonteiro** [comment]
> @hrqmonteiro did it reproduce with a min config?

Yes, it does. If i open goyo and disable galaxyline manually for the first time. Then i can toggle Goyo on and off as i please and it doesn't come back, but on the first time i open goyo, it does show up.

**Comment by glepnir** [comment]
I will test it later. thanks for report.

**Comment by hrqmonteiro** [comment]
Alright, thanks for support.

**Comment by levirs565** [comment]
Workaround to solve this problem is using vim.defer_fn . Like this:

```vim
function! s:goyo_enter()
  set noshowmode
  set noshowcmd
  lua vim.defer_fn(require("galaxyline").disable_galaxyline, 10)
endfunction

function! s:goyo_leave()
  set showmode
  set showcmd
  lua require("galaxyline").galaxyline_augroup()
endfunction

autocmd! User GoyoEnter call s:goyo_enter()
autocmd! User GoyoLeave call s:goyo_leave()

```

**Comment by hrqmonteiro** [comment]
I actually switched from goyo to [TrueZen](https://github.com/kdav5758/TrueZen.nvim), it's written on Lua and works better than Goyo, including the behaviour with galaxyline.

**Comment by sprainbrains** [comment]
> Workaround to solve this problem is using vim.defer_fn . Like this:
> 
> ```viml
> function! s:goyo_enter()
>   set noshowmode
>   set noshowcmd
>   lua vim.defer_fn(require("galaxyline").disable_galaxyline, 10)
> endfunction
> 
> function! s:goyo_leave()
>   set showmode
>   set showcmd
>   lua require("galaxyline").galaxyline_augroup()
> endfunction
> 
> autocmd! User GoyoEnter call s:goyo_enter()
> autocmd! User GoyoLeave call s:goyo_leave()
> ```

in my case i improved your code for s:goyo_leave() function

```viml 
function! s:goyo_leave()
  set showmode
  set showcmd
  lua vim.defer_fn(require("galaxyline").load_galaxyline, 10)
endfunction 
```
