### ISSUE TITLE
errors on NeoVim HEAD

### ISSUE THREAD

**Issue by iwata** [glepnir/galaxyline.nvim#35]
I'm using the following versions of NeoVim.
And `buf_diagnostics_count is deprecated. Use 'vim.lsp.diagnostic.get_count'` error occurred.

```
$ nvim -version      
NVIM v0.5.0-35325ddac
Build type: Release
LuaJIT 2.0.5
```

**Comment by glepnir** [comment]
@iwata the new change of lsp in head version. I will add it support later.

**Comment by iwata** [comment]
Okay, thanks for the prompt reply!

**Comment by glepnir** [comment]
@iwata  fixed.
