### ISSUE TITLE
Highlights not working

### ISSUE THREAD

**Issue by weilbith** [glepnir/galaxyline.nvim#39]
Hi,
thanks for this cool plugin and the nice approach.
I just started, but colors do not work for me. Do need to set any vim option?

Here a minimal configuration of the plugin:

```lua
local section = require('galaxyline').section

section.left[1] = {
  test = {
    provider = function() return 'test' end,
    highlight = { '#ff0000a', '#00ff00' },
  }
}
```

**Comment by glepnir** [comment]
@weilbith   I don't think this hex code  `#ff0000a`  can be read.  Did you mean `#ff0000` ?

**Comment by weilbith** [comment]
Sorry, that was just typo. 🙈
It doesn't change anything when I remove the `a`.

**Comment by glepnir** [comment]
Ok, should be check these settings
```vim
set laststatus=2
set termguicolors
```

**Comment by weilbith** [comment]
Oh damn. I haven't set `termguicolors`. Was that documented? :thinking:
Anyway, thanks for the quick help!

**Comment by glepnir** [comment]
Aha not documented.. we can used true color in terminal by config `termguicolors` .so I think that everyone should be config it.
