### ISSUE TITLE
Sourcing init.vim temporarily breaks statusline

### ISSUE THREAD

**Issue by ranebrown** [glepnir/galaxyline.nvim#40]
If you `so init.vim` the statusline colors seem to disable and some extra separator icons get added. This seems to resolve itself after switching buffers and the statusline being refreshed. This does require opening a new buffer if you only have one open.

**Comment by glepnir** [comment]
hmmm I don't know what you mean. can you give me a reproduce step.

**Comment by ranebrown** [comment]
Sure. This is using the eviline example.

1. `nvim ~/.config/nvim/init.vim`
2. All looks good
    <img width="713" alt="1" src="https://user-images.githubusercontent.com/10778249/99878056-ea06e380-2bbf-11eb-844e-53e0c324c290.png">
3. `source %`
3. Things look wacky.
    <img width="714" alt="2" src="https://user-images.githubusercontent.com/10778249/99878067-10c51a00-2bc0-11eb-9936-2d10bb1f8d33.png">

**Comment by glepnir** [comment]
Can't reproduce . need a minial config to reproduce.
![after](https://user-images.githubusercontent.com/41671631/99878161-6f30dd80-2c3e-11eb-9f70-77763f9cd005.gif)

**Comment by ranebrown** [comment]
I haven't been able to 100% reproduce with a minimal config but it seems like it might be related to `termguicolors`. Using the below minimal settings you should see something similar if you remove the `set termguicolors`.

```vim
set packpath=
set rtp+=$PWD/nvim-web-devicons
set rtp+=$PWD/galaxyline.nvim
lua require('eviline')
set termguicolors
```

**Comment by ranebrown** [comment]
Related to the colorscheme. I'm using [oceanicnext](https://github.com/adrian5/oceanic-next-vim):

```vim
set packpath=
set rtp+=$PWD/nvim-web-devicons
set rtp+=$PWD/galaxyline.nvim
set rtp+=$PWD/oceanic-next-vim
lua require('eviline')
set termguicolors
colorscheme oceanicnext
```

**Comment by glepnir** [comment]
I can't reproduce with this min config. so maybe not galaxyline problem closed.
```vim
set rtp+=$PWD/nvim-web-devicons
set rtp+=$PWD/galaxyline.nvim
lua require('eviline')
set termguicolors
```
![after](https://user-images.githubusercontent.com/41671631/99879029-8d014100-2c44-11eb-9bf3-cf8dc12ebbef.gif)

**Comment by ranebrown** [comment]
I think this should be reopened. The same issue is present with a variety of popular colorshemes. All of the below colorschemes except your zephyr theme result in the issue.

```vim
set packpath=
set rtp+=$PWD/nvim-web-devicons
set rtp+=$PWD/galaxyline.nvim
set rtp+=$PWD/oceanic-next-vim
set rtp+=$PWD/vim-colors-solarized
set rtp+=$PWD/zephyr-nvim
set rtp+=$PWD/gruvbox
lua require('eviline')
set termguicolors
colorscheme gruvbox
```

**Comment by glepnir** [comment]
I said this is truly min vim config ,If this can't reproduce  I think that mean not galaxyline problem. I don't work for other plugin.
```vim
set rtp+=$PWD/nvim-web-devicons
set rtp+=$PWD/galaxyline.nvim
lua require('eviline')
set termguicolors
``

**Comment by ranebrown** [comment]
I don't think any of the default colorschemes use true color so I don't know if it is fair to use them for testing. Your going to drive people away from using your plugin if it can't support other colorschemes. I guess that's your choice though and maybe you don't care.

**Comment by glepnir** [comment]
oh really？ other galaylineusers use different themes and they got fine. If truly config can't reproduce. I don't think it's galaxyline problem by the way theme just set some group colors you can custom.  you can choose other statusline plugin that you likr.
