### ISSUE TITLE
A bug occurs when using vista

### ISSUE THREAD

**Issue by Adnios** [glepnir/galaxyline.nvim#44]
1. :Vista!!
![image](https://user-images.githubusercontent.com/41060790/101232371-53bcdc80-36ec-11eb-9187-4cb7ba87fe55.png)
2. Put the cursor in VISTA's window and :Vista!!
![image](https://user-images.githubusercontent.com/41060790/101232446-7cdd6d00-36ec-11eb-90a0-e21101dad6f6.png)

The galaxyline.nvim didn't go back to what you were before.

But if I put the cursor in myfile.h's window and :Vista!! It work well

My vim config file:
```
luafile ~/.config/nvim/plugged/galaxyline.nvim/example/eviline.lua
```

**Comment by glepnir** [comment]
@Adnios  this is except behavior. cause you trigger the `Winleave` autocmd then galaxyline will use the 
`short_line` ,if you want to see more things. you can config short_line.
