### ISSUE TITLE
Statusline change diagnostic signcolumn color

### ISSUE THREAD

**Issue by etrnal70** [glepnir/galaxyline.nvim#48]
With the plugin, diagnostic signcolumn turns gray. Maybe conflicting color group ? 
![image](https://user-images.githubusercontent.com/5826834/102012567-cded0100-3d7d-11eb-90e0-2e15689e5b45.png)
![image](https://user-images.githubusercontent.com/5826834/102012598-e230fe00-3d7d-11eb-9a65-f9b028cc904d.png)

**Comment by glepnir** [comment]
hmm  all the color group of diagnostic has prefix  Galaxy. and I think you should check problem with a minal config. can't reproduce your problem
