### ISSUE TITLE
Powerline symbol scaling

### ISSUE THREAD

**Issue by dm19** [glepnir/galaxyline.nvim#49]
Maybe this doesn't have anything to do with the plugin itself, but for some reason powerline symbol separators are not the right size in my statusline. I'm using nerd font patched Jetbrains Mono, and the symbols are the right size in the buffer text, but not on the statusline. 

![Screenshot_20201217_004201](https://user-images.githubusercontent.com/31514792/102448927-26800080-4001-11eb-9755-e840b3f5df8e.png)

I know in spacemacs scaling for powerline symbols was a configuration option. I don't know enough about vim to know if that's an issue or an option here.

**Comment by glepnir** [comment]
@dm19  Gui emacs use xmap to generate separator. terminal doesn't support xmap. change your nerd font. Because the symbol does not work fine with every font.

**Comment by dm19** [comment]
Ah, I was using the wrong version of Nerd Font (JetbrainsMono Nerd Font instead of JetbrainsMono Nerd Font Mono). Using the true monospaced version fixed the size issues.
