### ISSUE TITLE
Question: Colorscheme examples

### ISSUE THREAD

**Issue by matu3ba** [glepnir/galaxyline.nvim#55]
```
local colors = {
  bg = '#282c34',
  line_bg = '#353644',
  fg = '#8FBCBB',
  fg_green = '#65a380',

  yellow = '#fabd2f',
  cyan = '#008080',
  darkblue = '#081633',
  green = '#afd700',
  orange = '#FF8800',
  purple = '#5d4d7a',
  magenta = '#c678dd',
  blue = '#51afef';
  red = '#ec5f67'
}
```

1. fg_green is unused in both examples. What was planned to use it for?

2. Even complicated color schemes [use normal colors](https://github.com/altercation/vim-colors-solarized/blob/528a59f26d12278698bb946f8fb82a63711eec21/colors/solarized.vim#L267). Can we collect all colors of color schemes, such that one can copy-paste them and prototype them abit? [Potential list of colors](https://github.com/rafi/awesome-vim-colorschemes).

**Comment by glepnir** [comment]
`fg_green` used in `eviline.lua`. yep we can collect some colors  like `onedark gruvbox` and so on. maybe add it in wiki page ?

**Comment by matu3ba** [comment]
@glepnir You need to create a wiki for editing. Github does host the wiki externally as to not interfere with regular commits.

**Comment by matu3ba** [comment]
@glepnir ping, you need to create a wiki or I can not put things inside.

**Comment by glepnir** [comment]
Thanks .I create it. you can git clone wiki

**Comment by glepnir** [comment]
now built-in support

**Comment by matu3ba** [comment]
@glepnir I can not edit the wiki imho.

**Comment by glepnir** [comment]
hmm I mean support in code  usage
```lua
-- built-in theme
local colors = require('galaxyline.theme').default
highlight = { colors.bg/fg/yellow/....}
-- color hex code
bg = '#202328',
fg = '#bbc2cf',
yellow = '#ECBE7B',
cyan = '#008080',
darkblue = '#081633',
green = '#98be65',
orange = '#FF8800',
violet = '#a9a1e1',
magenta = '#c678dd',
blue = '#51afef';
red = '#ec5f67';
```
