### ISSUE TITLE
Attempt to compare number with nil

### ISSUE THREAD

**Issue by DuGlaser** [glepnir/galaxyline.nvim#58]
Thanks for the great plugin!

But, when I use galaxyline.nvim with the latest nvim, I get the following error.
This error did not occur until recently.
```
...er/start/galaxyline.nvim/lua/galaxyline/provider_vcs.lua:178: attempt to compare number with nil
E15: Invalid expression: luaeval('require("galaxyline").component_decorator')("DiffAdd")
```

## Environment
OS: Ubuntu
Nvim:
```
NVIM v0.5.0-dev+1000-g84d08358b
Build type: Release
LuaJIT 2.1.0-beta3
```
galaxyline.nvim: use 9fdebfbb95189b099b470e8e8ff7f0b87298e0f0
nvim setting: https://github.com/DuGlaser/nvim_setting

**Comment by DuGlaser** [comment]
This error seems to occur when 'DiffAdd', 'DiffModified', or 'DiffRemove' is used.

**Comment by glepnir** [comment]
which git plugin do you used ？

**Comment by DuGlaser** [comment]
https://github.com/lewis6991/gitsigns.nvim
I was using gitsigns.
I tried disabling gitsings and the error disappeared, so maybe it's a problem with gitsings.
Sorry :pray:

**Comment by DuGlaser** [comment]
Apparently, it was an gitsings problem.
At point https://github.com/lewis6991/gitsigns.nvim/commit/9c49451bfd85f397b38ec2362674ac06bf9f3d36 , it worked fine.

**Comment by glepnir** [comment]
@DuGlaser  I had update vcs for last gitsigns change. so you can update.

**Comment by DuGlaser** [comment]
Thank you!
I updated and it's fixed now!
