### ISSUE TITLE
Latest gitsigns results in an error from provider_vcs

### ISSUE THREAD

**Issue by SanchayanMaity** [glepnir/galaxyline.nvim#59]
The latest [commit](https://github.com/lewis6991/gitsigns.nvim/commit/c6f9d2e89595f97900676d4dad324f71f3c4d85b) gives an error in `provider_vcs.lua`.  The error primarily comes from line number 178. My lua skills are non existent but it seems like the way to retrieve the signs data has changed?

**Comment by glepnir** [comment]
@SanchayanMaity  see #58

**Comment by SanchayanMaity** [comment]
@glepnir Thanks. Am currently doing the same, by reverting the commit locally.

**Comment by glepnir** [comment]
@SanchayanMaity    I had update vcs for last gitsigns change. so you can update.

**Comment by SanchayanMaity** [comment]
@glepnir It's fixed. Thank you very much.
