### ISSUE TITLE
nvim crashing with GitBranch provider

### ISSUE THREAD

**Issue by salkin-mada** [glepnir/galaxyline.nvim#6]
## version
NVIM v0.5.0-767-g0f590ae2a
Lua 5.4.1
LuaJIT 2.1.0-beta3

## issue
using the following provider will crash nvim if opening a session, file etc. in a non .git directory.
```
gls.left[6] = {
  GitBranch = {
    provider = 'GitBranch',
    condition = empty_buffer,
    highlight = {colors.grey,colors.purple},
  }
}
```

* (as an example) `pwd` = $HOME
then `cd ~ && nvim some_new_file_which_is_not_in_a_git_repo` will hang nvim.

**Comment by glepnir** [comment]
should be fixed.

**Comment by salkin-mada** [comment]
**Thanks!**
maybe i am wrong - but I think we need to check if the path is a git repo in a different way?
though commit **b544f1c** fixes the issue for `$HOME`. -> When using `nvim` for general tasks all over the system directory -just as normal usage with sudo or via `sudoedit` this is still at problem. try `nvim something_random` in `/home/` or `/etc/` then heavy cpu usage and nvim/terminal hanging/crashing is still an issue. If i am not mistaking.

here `echo $EDITOR` is nvim - i use it everywhere.
so this git branch checking should somehow be "non-aggressive"

* --?
not a fix of the "Provider" (vcs) in `galaxyline` but a related question.
how would I use `FugitiveHead()` ('tpope/vim-fugitive') in the same way i would use it in lets say `lightline`?

```
local api = vim.api
local gl = require('galaxyline')
local gls = gl.section

local empty_buffer = function()
	if vim.fn.empty(vim.fn.expand('%:t')) ~= 1 then
		return true
	end
	return false
end

gls.right[1] = {
  GitHead = {
    provider = function()
		local branch = api.nvim_command(':call FugitiveHead()')
		return branch
	end,
    condition = empty_buffer,
    highlight = { '#0087d7','#d16d9e'},
  }
}
```

**Comment by glepnir** [comment]
yes. I only check the path equal `$HOME` .. so if you edit some `/etc` it will cause some problem.
you should use `vim.fn.FugitiveHead()` get the result.

**Comment by salkin-mada** [comment]
nice - thanks. I am basically learning `lua` as we speak :) porting my init.vim to lua.

**Comment by glepnir** [comment]
Should be rewrite `find_git_root` function .

**Comment by glepnir** [comment]
I had rewrite it. can you test it?

**Comment by salkin-mada** [comment]
cool. just updated. now `nvim` with `galaxyline.nvim` using the default provider 'GitBranch' works everywhere and with `sudoedit`.
i just edited `sudoedit /etc/pulse/default.pa` succesfully using `statusline.lua.`  :-)

 great work!
