### ISSUE TITLE
inconsistent visibility in buffers

### ISSUE THREAD

**Issue by Adictya** [glepnir/galaxyline.nvim#64]
I really like the plugin however I am facing an issue where the galaxy line is not visible upon initial execution of neovim. If I call a buffer refresh via something like whichkey window in the example , it becomes visible. However on opening a neo-tree split-buffer it disappears again only to come after I close that split-buffer

Demonstration.
![galaxyvimissue](https://user-images.githubusercontent.com/14136384/103911210-c249eb80-512b-11eb-9764-41ccbe6df88c.gif)

Issue Reproduction-
This is [my config](https://github.com/Adictya/Nvim-config/blob/master/init.vim)
The issue seems to be theme agnostic however I am using [this](https://github.com/glepnir/galaxyline.nvim/issues/12#issuecomment-719999127) theme
I have done no additional customizations besides loading the theme on my part

**Comment by glepnir** [comment]
config `gl.short_line_list ` is a table value is some special buffer filetypes. when you in this buffer will show short_line. so you need config short_line . Also when you trigger `WinLeave` ,it also load short_line
```lua
-- if in LuaTree or vista or dbui buffer will load short_line
gl.short_line_list = {'LuaTree','vista','dbui'}

gls.short_line_left[1] = {
  BufferType = {
    provider = 'FileTypeName',
    separator = '',
    separator_highlight = {colors.purple,colors.bg},
    highlight = {colors.fg,colors.purple}
  }
}


gls.short_line_right[1] = {
  BufferIcon = {
    provider= 'BufferIcon',
    separator = '',
    separator_highlight = {colors.purple,colors.bg},
    highlight = {colors.fg,colors.purple}
  }
}
```
check your config short_line just return a empty .so you don't see anything.

**Comment by Adictya** [comment]
Apologies for not reading the documentation , thank you for your fixes that seems to have fixed most of my issue.

**Comment by glepnir** [comment]
Aha It's okay. now I will close this issue.
