### ISSUE TITLE
race conditions

### ISSUE THREAD

**Issue by davidsu** [glepnir/galaxyline.nvim#65]
I'm giving this a go, have to say I love it!!!
I've been having to code some workarounds though.
Issues happen on entering `fzf` and `terminal` windows. I started out with spaceline and soon saw that sometimes in terminal buffers there is no branchName but the git icon is still there. Started investigating, the logic `buffer_not_empty` isn't the same as `vcs.get_git_branch`.
"Fair enough", I thought to myself, let's change the condition for GitIcon to be `vcs.get_git_branch`. Still get sometimes the icon there and no gitBranchName. So I decided that the GitIcon will need to have the following provider
```lua
function() 
  if(vcs.get_git_branch()) then 
    return ' THE_ICON ' 
  end 
  return ''
end
```
Ok, that solves that, now I'm battling the filename. Opening `:term` I get empty filename, go to some other file and back, now I get the desired `zsh`. I'll probably try to call `load_galaxyline` after `n ms` for `mode() == 't'` to workaround this(will need to watch not to enter an infinite loop).
I'm guessing that all these events `'FileType','BufWinEnter','BufReadPost','BufWritePost','BufEnter','WinEnter','FileChangedShellPost','VimResized' ` fire very quickly one after another, I'd imagine that `debouncing` the call to `load_galaxyline` would solve the problem.
Having said that, that's my first time writing any lua, I'm just getting my feet wet. I see there is a `defer_fn` function, I don't see a `debounce` but shouldn't be too hard to implement one.

Thanks for the amazing work!

**Comment by glepnir** [comment]
@davidsu  now you want when you open temrinal in neovim show terminal in statusline?

>now I get the desired zsh. I'll probably try to call load_galaxyline after n ms for mode() == 't' to workaround this(will need to watch not to enter an infinite loop).

can you show a pic of this problem?

**Comment by davidsu** [comment]
<img width="513" alt="Screen Shot 2021-01-09 at 12 40 23" src="https://user-images.githubusercontent.com/4605383/104089464-f3cfcd80-5277-11eb-826b-0ae6728b45b6.png">
above using the examples spaceline, first terminal render

<img width="530" alt="Screen Shot 2021-01-09 at 12 43 58" src="https://user-images.githubusercontent.com/4605383/104089503-5cb74580-5278-11eb-97ce-1d3af3304888.png">

you see that on first the "filename" section is empty, after "losing focus" and "regaining" it it gets populated with `zsh`, and on second render the gitIcon is present even though there's no gitBranch. It doesn't feel proper.

**Comment by glepnir** [comment]
@davidsu  Please update
