### ISSUE TITLE
filename on splitwindow

### ISSUE THREAD

**Issue by davidsu** [glepnir/galaxyline.nvim#67]
I really need to see the filepath on splitwindows, looks like by design `inactive_galaxyline` greys out non-focused window.
Can I get the filepath displayed there?

**Comment by glepnir** [comment]
you can config short_ right

**Comment by davidsu** [comment]
that's perfect, thanks a lot!

**Comment by glepnir** [comment]
now can we close this issue?

**Comment by davidsu** [comment]
Yes, 10x
