### ISSUE TITLE
Opening a .h C header file gives error

### ISSUE THREAD

**Issue by SanchayanMaity** [glepnir/galaxyline.nvim#7]
Am currently using the `spaceline` example almost as is.

While opening a C header file with .h extension, I get the following error

```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ... pack/paqs/start/galaxyline.nvim/lua/galaxyline/colors.lua:13 attempt to concatenate a nil value
```

This doesn't happen for any other files I have tried so far.

**Comment by glepnir** [comment]
fixed.
