### ISSUE TITLE
Request: Add support for more than just section_left and section_right

### ISSUE THREAD

**Issue by runiq** [glepnir/galaxyline.nvim#70]
Hi, thanks for galaxyline! :+1: 

See the subject line: Would you consider adding support for more than `section_left`/`right`? It looks like both are [concatenated using `%=` anyways](https://github.com/glepnir/galaxyline.nvim/blob/5ce0360308aded6e54af9d5a21b908e619ccb5e9/lua/galaxyline.lua#L220-L223), so I hope it wouldn't be too hard to add some other section.

My use case: I used to have a statusline that had most stuff displayed in the middle instead of the left and right, so having another section would be convenient. :)

**Comment by glepnir** [comment]
yep . it can be support.

**Comment by runiq** [comment]
Good to hear :) How about this:

1. If there are no unnamed sections in `sections`, just concatenate `section_left`/`right` using `%=` (as it is done now)
2. Concatenate all unnamed sections in `sections`, in order, with `%=`
3. If `section_left`/`section_right` exist, prepend/append them using `%=` too

That would keep current configs working.

Does that sound reasonable?

**Comment by glepnir** [comment]
@runiq  Hey can you provide a min statusline code snippet that set some text in statusline mid

**Comment by mnabila** [comment]
@glepnir could you add new section for inactive statusline ? i think this very userfull if someone want change style diferent between section.short_line_left and inactive statusline 

thanks

**Comment by glepnir** [comment]
now it's support but a little troublesome . do it in provider 

```
provider = function()
  -- if true in special buffer
   if hasvalue(shortlist,vim.bo.filetype) then
       show some text
   else
       -- it will show in inactive statusline
       show text
  end
end
```

like i do it in here https://github.com/glepnir/galaxyline.nvim/blob/dd1cd3098f95423fa744be5d65b61132caae51b5/lua/galaxyline/provider_fileinfo.lua#L178

work like this.
![image](https://user-images.githubusercontent.com/41671631/110232458-af4f6e00-7f58-11eb-919f-e8e0d7b55d51.png)

so you can config inactive line in short_line.

**Comment by mnabila** [comment]
@glepnir nice its work
![image](https://user-images.githubusercontent.com/37516576/110260912-ac985b80-7fe0-11eb-86df-5ebf938506ea.png)

**Comment by glepnir** [comment]
@mnabila  a tips that you can use `vim.fn.index` function. like

```lua
if vim.fn.index(short_list,vim.bo.filetype) ~= -1 then
```

**Comment by mnabila** [comment]
@glepnir  thanks for your tips :+1:

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/110271621-5f79b100-8003-11eb-8eb5-f8199c024937.png)

**Comment by mnabila** [comment]
@glepnir adding mid options in section  short_line :laughing: 

:runner:  :runner:  :runner:  :runner:  :runner:

**Comment by runiq** [comment]
Sorry I didn't ever get around to this @glepnir :( Thanks a lot for implementing it!

**Comment by glepnir** [comment]
It's okay .my person usage

![image](https://user-images.githubusercontent.com/41671631/110287014-d1acbe80-8020-11eb-841b-e17de54b7562.png)

**Comment by niloco** [comment]
Any chance of centering the middle section relative to the buffer instead of the other two sections? If we know the width of the left section, middle section and window width we could compute the correct amount of padding to do it. 
Theoretically we could then do something like `line = left_section..padding..mid_section..right_section`.
What do you think about that?

**Comment by glepnir** [comment]
yep can get the padding value . But I want to know how it is different from the current behavior

**Comment by niloco** [comment]
Here's an example:
![image](https://user-images.githubusercontent.com/38590179/110407508-f0777900-8051-11eb-9cc6-fc98a74e6c71.png)
Top is centered on the whole bar, bottom is centered between the mode indicator and the pink branch logo. There's more of a difference with left and right sections that are lopsided.

**Comment by glepnir** [comment]
default behavior is a bit to the right.  If there are too many components in the left area. The window just accommodates all the components. Then the behavior of centering the buffer will make the left side appear a bit crowded.In the second way, we need to recalculate the value of pad when the width of the buffer window changes. This requires binding some autocmd

**Comment by niloco** [comment]
It appears that the status line is already redrawn on size changes, so no need to worry about that.
