### ISSUE TITLE
Error when run nvim

### ISSUE THREAD

**Issue by ivano9** [glepnir/galaxyline.nvim#78]
Hi, any idea why i get this error?
neovim version: NVIM v0.5.0-dev+1025-g0fad952a2
SO: Ubuntu 20.04.1

![image](https://user-images.githubusercontent.com/43305758/105376134-2cf92d80-5be8-11eb-85be-7d9b100ed052.png)

**Comment by glepnir** [comment]
@ivano9  I think you build from source?

**Comment by ivano9** [comment]
Sorry for my ignorance, how i do it?

**Comment by glepnir** [comment]
I mean your neovim build from source?

**Comment by ivano9** [comment]
I installed neovim with the neovim.appimage, i just changed name to nvim and move it in the path /usr/local/bin/nvim

**Comment by glepnir** [comment]
Okay.it should be problem of neovim.appimage.

**Comment by ivano9** [comment]
I think i fix the problem, the nvim didn't work fine coz the environment variables $VIMRUNTIME and $VIM didn't set...
I just did, export VIMRUNTIME=/usr/local/share/nvim/runtime and VIM=/usr/local/share/nvim/ and then reboot.
The error disappeared after that and now can configure the galaxyline w/o problem. 
Tyvm.
