### ISSUE TITLE
cterm support

### ISSUE THREAD

**Issue by jdhaggerty** [glepnir/galaxyline.nvim#79]
It would be nice to set cterm highlights as well. Right now, in a terminal emulator, the status lines are all black and white.

**Comment by glepnir** [comment]
@jdhaggerty Do we really need to add cterm support? Most of  current terminals and neovim support true color you can set the  `termguicolors` .

**Comment by jdhaggerty** [comment]
I stand corrected. All this time, and I didn't know about termguicolors.
