### ISSUE TITLE
E15: Inavild expression: luaeval('require("galaxyline").component_decorator')("VIMode")

### ISSUE THREAD

**Issue by rustiever** [glepnir/galaxyline.nvim#81]
while using the `hrsh7th/vim-vsnip` this plugin I'm getting this error.

###here is my status line config
local gl = require('galaxyline')
local utils = require('utils')

local gls = gl.section
gl.short_line_list = { 'defx', 'packager', 'vista' }

-- Colors
local colors = {
    bg = '#282a36',
    fg = '#f8f8f2',
    section_bg = '#38393f',
    yellow = '#f1fa8c',
    cyan = '#8be9fd',
    green = '#50fa7b',
    orange = '#ffb86c',
    magenta = '#ff79c6',
    blue = '#8be9fd',
    red = '#ff5555'
}

-- Local helper functions
local buffer_not_empty = function()
    return not utils.is_buffer_empty()
end

local checkwidth = function()
    return utils.has_width_gt(40) and buffer_not_empty()
end

local mode_color = function()
    local mode_colors = {
        n = colors.cyan,
        i = colors.green,
        c = colors.orange,
        V = colors.magenta,
        [''] = colors.magenta,
        v = colors.magenta,
        R = colors.red,
    }

    return mode_colors[vim.fn.mode()]
end

-- Left side
gls.left[1] = {
    FirstElement = {
        provider = function() return '‚ñã' end,
        highlight = { colors.cyan, colors.section_bg }
    },
}
gls.left[2] = {
    ViMode = {
        provider = function()
            local alias = {
                n = 'NORMAL',
                i = 'INSERT',
                c = 'COMMAND',
                V = 'VISUAL',
                [''] = 'VISUAL',
                v = 'VISUAL',
                R = 'REPLACE',
            }
            vim.api.nvim_command('hi GalaxyViMode guifg='..mode_color())
            return alias[vim.fn.mode()]..' '
        end,
        highlight = { colors.bg, colors.bg },
        separator = "ÓÇ∏  ",
        separator_highlight = {colors.bg, colors.section_bg},
    },
}
gls.left[3] ={
    FileIcon = {
        provider = 'FileIcon',
        condition = buffer_not_empty,
        highlight = { require('galaxyline.provider_fileinfo').get_file_icon_color, colors.section_bg },
    },
}
gls.left[4] = {
    FileName = {
        provider = { 'FileName', 'FileSize' },
        condition = buffer_not_empty,
        highlight = { colors.fg, colors.section_bg },
        separator = "ÓÇ∏ ",
        separator_highlight = {colors.section_bg, colors.bg},
    }
}
gls.left[5] = {
    GitIcon = {
        provider = function() return ' Ôû° ' end,
        condition = buffer_not_empty,
        highlight = {colors.red,colors.bg},
    }
}
gls.left[6] = {
    GitBranch = {
        provider = 'GitBranch',
        condition = buffer_not_empty,
        highlight = {colors.fg,colors.bg},
    }
}
gls.left[7] = {
    DiffAdd = {
        provider = 'DiffAdd',
        condition = checkwidth,
        icon = 'Ôëó ',
        highlight = { colors.green, colors.bg },
    }
}
gls.left[8] = {
    DiffModified = {
        provider = 'DiffModified',
        condition = checkwidth,
        icon = 'Ôëô ',
        highlight = { colors.orange, colors.bg },
    }
}
gls.left[9] = {
    DiffRemove = {
        provider = 'DiffRemove',
        condition = checkwidth,
        icon = 'Ôëò ',
        highlight = { colors.red,colors.bg },
    }
}
gls.left[10] = {
    LeftEnd = {
        provider = function() return 'ÓÇ∫ ' end,
        condition = buffer_not_empty,
        highlight = {colors.section_bg,colors.bg}
    }
}
gls.left[11] = {
    DiagnosticError = {
        provider = 'DiagnosticError',
        icon = ' ÔÅó ',
        highlight = {colors.red,colors.section_bg}
    }
}
gls.left[12] = {
    Space = {
        provider = function () return ' ' end,
        highlight = {colors.section_bg,colors.section_bg},
    }
}
gls.left[13] = {
    DiagnosticWarn = {
        provider = 'DiagnosticWarn',
        icon = ' ÔÅ± ',
        highlight = {colors.orange,colors.section_bg},
    }
}
gls.left[14] = {
    Space = {
        provider = function () return ' ' end,
        highlight = {colors.section_bg,colors.section_bg},
    }
}
gls.left[15] = {
    DiagnosticInfo = {
        provider = 'DiagnosticInfo',
        icon = ' ÔÅö ',
        highlight = {colors.blue,colors.section_bg},
        separator = 'ÓÇ∏ ',
        separator_highlight = { colors.section_bg, colors.bg },
    }
}

-- Right side
gls.right[1]= {
    FileFormat = {
        provider = function() return vim.bo.filetype end,
        highlight = { colors.fg,colors.section_bg },
        separator = 'ÓÇ∫ ',
        separator_highlight = { colors.section_bg,colors.bg },
    }
}
gls.right[2] = {
    LineInfo = {
        provider = 'LineColumn',
        highlight = { colors.fg, colors.section_bg },
        separator = ' | ',
        separator_highlight = { colors.bg, colors.section_bg },
    },
}
gls.right[3] = {
    Percent = {
        provider = 'ScrollBar',
        highlight = { colors.fg, colors.section_bg },
        separator = ' | ',
        separator_highlight = { colors.bg, colors.section_bg },
    }
}

-- Short status line
gls.short_line_left[1] = {
    BufferType = {
        provider = 'FileTypeName',
        highlight = { colors.fg, colors.section_bg },
        separator = 'ÓÇ∏ ',
        separator_highlight = { colors.section_bg, colors.bg },
    }
}

gls.short_line_right[1] = {
    BufferIcon = {
        provider= 'BufferIcon',
        highlight = { colors.yellow, colors.section_bg },
        separator = 'ÓÇ∫ ',
        separator_highlight = { colors.section_bg, colors.bg },
    }
}

-- Force manual load so that nvim boots with a status line
gl.load_galaxyline()

**Comment by glepnir** [comment]
your vim mode miss some mode value，check the emaple/eviline.lua vimmode section.
