### ISSUE TITLE
Event Setting

### ISSUE THREAD

**Issue by fdschmidt93** [glepnir/galaxyline.nvim#83]
Hello,

thanks for a really cool plugin! First time using lua to configure neovim and it's quite fun :)

I am trying to pipe shell output into the status line and was hoping that the event 'BufEnter' would ensure that the specific segment was only loaded during the BufEnter event. However, it is obviously not working since neovim becomes extremely slow whenever I include the system call. Circumventing repeated outputs by assigning the output to a string variable reduces the slow down, but I was hoping to eventually also test for the python file type and otherwise return an empty string.

```
  local conda_env = function ()
    conda_environment = vim.fn.system('echo $CONDA_PROMPT_MODIFIER'):sub(1, -2)   -- remove final 2 characters to clean up string
    return conda_environment
  end
  
  gls.left[16] = {
    CondaEnv = {
    provider = CondaEnv,
    highlight = {colors.bright_green, colors.bg},
    event = 'BufEnter'
    }
  }
```

Any pointers would be appreciated! Many thanks in advance.

**Comment by glepnir** [comment]
you don't need to config event, because galaxyline has support bufenter. use `os.getenv("CONDA_PROMPT_MODIFIER")` will be better.

**Comment by fdschmidt93** [comment]
Works like a charm. Leaving the snippet below and updated issue title accordingly, if helpful to anyone. 
Thanks again!
```
-- get output from shell command
function os.capture(cmd, raw)
  local f = assert(io.popen(cmd, 'r'))
  local s = assert(f:read('*a'))
  f:close()
  if raw then return s end
  s = string.gsub(s, '^%s+', '')
  s = string.gsub(s, '%s+$', '')
  s = string.gsub(s, '[\n\r]+', ' ')
  return s
end

local CondaEnv = function ()
  if vim.bo.filetype == 'python' then
      conda = os.getenv('CONDA_PROMPT_MODIFIER')
      if conda ~= nil then
          python = os.capture('python -V')
          return python .. ' ' .. conda
      end
   return ''
    end
end
```
Results in e.g. "Python 3.8.5 (base)"
