### ISSUE TITLE
Provider not respecting condition on start, then duplicates the text

### ISSUE THREAD

**Issue by joshuachp** [glepnir/galaxyline.nvim#85]
The following provider will show up when opening any file then it will be duplicated when modifying the file
```lua
gls.left[4] = {
    FileModified = {
        provider = function () return ' ' end,
        confition = function ()
            if vim.bo.modified then
                return true
            end
            return false
        end,
        highlight = {colors.fg4, colors.bg2},
    }
}
```
To fix i needed to check before printing:
```lua
...
        provider = function ()
            if vim.bo.modified then
                return ' '
            else
                return ''
            end
        end,
...
```
File opened
![image](https://user-images.githubusercontent.com/43700905/106266835-378b7680-6229-11eb-8fcc-796671d98a20.png)
After modifying the file
![image](https://user-images.githubusercontent.com/43700905/106266964-525deb00-6229-11eb-9f3e-3147e6e0d7f2.png)

**Comment by joshuachp** [comment]
I don't know what changed but after adding the check it will still appear double when modified, but not when opened
![image](https://user-images.githubusercontent.com/43700905/106267936-aae1b800-622a-11eb-9bbb-b37464713873.png)

**Comment by glepnir** [comment]
can you provide a min code that can reproduce it.

**Comment by joshuachp** [comment]
Sorry, I was using `fileinfo.get_current_file_name()` which already provides modified. I noticed only when opening a read only file, my bad. Maybe it could be added to the README what each provider returns for a better ease of use.
Thank for your hard work :smile:

**Comment by glepnir** [comment]
Ok. I will supplement the document in detail when I have time.
