### ISSUE TITLE
Missing argument for guibg

### ISSUE THREAD

**Issue by Iron-E** [glepnir/galaxyline.nvim#86]
When opening certain filetypes (such as C# files) I get the following error message:

```log
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua ...ack/packer/opt/galaxyline.nvim/lua/galaxyline/colors.lua:44: Vim(highlight):E417: missing argument: guibg=
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...ack/packer/opt/galaxyline.nvim/lua/galaxyline/colors.lua:44: Vim(highlight):E417: missing argument: guibg=
```

I believe this is caused by the filetype not having an associated color, and returning an empty string upon resolving some function. I created a patch for this error (which I will push) but it does not fix the filetype not having any colors.

**Comment by glepnir** [comment]
when merge that. we can close it right?

**Comment by Iron-E** [comment]
No, there's still an issue. The PR just made it so if users provide empty strings for a color it won't be interpreted as an invalid Vim command (which is a symptom of the issue).

I'll upload screenshots later!

**Comment by glepnir** [comment]
okay. provide a min code. that can reproduce it

**Comment by Iron-E** [comment]
Will do 👍

I'll make a separate issue for it as well since that error message in the OP did get fixed by the PR.
