### ISSUE TITLE
C# filetype not recognized

### ISSUE THREAD

**Issue by Iron-E** [glepnir/galaxyline.nvim#88]
# Introduction

Followup to #86.

I believe #86 was a symptom of this issue, rather than the cause of it. Fixing that issue was still something that was worth doing since it prevented some unwanted behavior that could happen again in the future.

# Reproduction

1. Specify the following setup for galaxyline:
	```lua
	vim.cmd 'set guicolors'
	local galaxyline = require('galaxyline')
	local section = galaxyline.section
	local get_file_icon_color = require('galaxyline/provider_fileinfo').get_file_icon_color

	section.right = -- section.left also works
	{
		{FileType = {
			provider = 'FileTypeName', -- FileIcon also works
			highlight = {"#202020", get_file_icon_color, 'bold'},
			separator = "<< ",
			separator_highlight = {get_file_icon_color, "#202020"},
		}},
	}
	```
2. Enter a file such as rust, markdown, lua, etc, and observe the `get_file_icon_color` gives a color:
	![cap](https://user-images.githubusercontent.com/36409591/106396076-bd4b2580-63d3-11eb-8bce-69aa4a18b775.png)
3. Enter a file with an unknown type, such as `foo.somethingsomething`, and see it gives the "unknown type" color:
	![cap](https://user-images.githubusercontent.com/36409591/106396097-deac1180-63d3-11eb-9bf1-db0f6fa26b0a.png)
4. Enter a C# file and notice that no file color is given:
	![cap](https://user-images.githubusercontent.com/36409591/106396114-faafb300-63d3-11eb-8401-b9f7e03bd7e8.png)

**Comment by glepnir** [comment]
`FileTypeName` should be `FileIcon` right?

**Comment by Iron-E** [comment]
Yeah i have set `guicolors`. Should have specified.

Also, both of the providers mentioned (file name and icon) exhibit this bug. I just used file type name for purpose of demonstration, so shouldn't be related to #82

**Comment by glepnir** [comment]
min code 
```vim
set rtp+=~/workstation/vim/galaxyline.nvim
set rtp+=~/.cache/vim/dein/repos/github.com/kyazdani42/nvim-web-devicons

set termguicolors
lua <<EOF
local galaxyline = require('galaxyline')
local section = galaxyline.section
local get_file_icon_color = require('galaxyline/provider_fileinfo').get_file_icon_color

section.right = -- section.left also works
{
	{FileType = {
		provider = 'FileIcon',
		highlight = {"#202020", get_file_icon_color, 'bold'},
		separator = "<< ",
		separator_highlight = {get_file_icon_color, "#202020"},
	}},
}
EOF
```
Run `hi GalaxyFileType` got this `GalaxyFileType xxx gui=bold guifg=#202020 guibg=#596706`
`hi DevIconCs` got this `DevIconCs      xxx guifg=#596706`.  


![image](https://user-images.githubusercontent.com/41671631/106411861-381e4a00-6481-11eb-82d5-d9e839cc0fcf.png)

**Comment by glepnir** [comment]
any update for this issue? Can close it?

**Comment by glepnir** [comment]
No update so close it. If still exist reopen this issue.

**Comment by Iron-E** [comment]
No I still have the issue. Was busy yesterday but I'm working on setting up Neovim on another machine today for testing.

That'll let me know whether or not it's just my machine that's bugged

**Comment by Iron-E** [comment]
Okay so the new setup acts the same as my Arch install. When I run `hi DevIconCs` I get the expected output, but running `hi GalaxyFileType` shows the same except for the `guibg`, which is `NONE`.

This leads back into the last issue where it's resolving to an empty string for some reason, so it was giving an error since you can't set `guibg=` nothing. So, the PR made it default to `NONE`. However now we need to figure out why it was resolving to an empty string in the first place

**Comment by glepnir** [comment]
I had rewrite color code. can you test it?

**Comment by Iron-E** [comment]
Sure thing! I'll try it out later today and get back to you

**Comment by Iron-E** [comment]
Just tried it, same result. I notice if I override the color for the background I can see the icon and filetype just fine, so we know that's working at least:

```lua
local hi = require 'highlite'
local galaxy_file_type = hi.group 'GalaxyFileType'
hi.highlight('GalaxyFileType', {fg=galaxy_file_type.fg, style=galaxy_file_type.style, bg='#9999FF'})
```

**Note:** you probably won't be able to run that snippet, I just used it since my colorscheme lets me quickly override one attribute of a highlight group; it's just an example.

**Comment by glepnir** [comment]
I don't know which is error?
```
section.right = -- section.left also works
{
	{FileType = {
		provider = 'FileTypeName', -- FileIcon also works
		highlight = {"#202020", get_file_icon_color, 'bold'},
		separator = "<< ",
		separator_highlight = {get_file_icon_color, "#202020"},
	}},
}
```
![image](https://user-images.githubusercontent.com/41671631/107141700-9fe30200-6965-11eb-8bc6-51d4a884815b.png)

```
highlight = {"#202020", get_file_icon_color, 'bold'},
--fg = #2020202 
--bg= lua print(get_file_icon_color()) == #596706
:hi GalaxyFileType
GalaxyFileType xxx gui=bold guifg=#202020 guibg=#596706

separator_highlight = {get_file_icon_color, "#202020"},
-- fg = lua print(get_file_icon_color()) == #596706
-- bg = "#202020"
:hi FileTypeSeparator
FileTypeSeparator xxx guifg=#596706 guibg=#202020
``

**Comment by Iron-E** [comment]
* When loading a file of any recognized type which is different than C#, I see the name of the file type + icon with the correct color background.
* When loading a file of any unrecognized type, I see the name of the file type and "unknown file" icon with the "unknown file" background color.
* When loading a C# file, there is no background color for the file type nor file name sections of the statusline, and so it shows as blank even though the file name and file type are actually being rendered.

In the original comment I showed the error with three screenshots. In the previous comment I also linked to the file and line number where I believe this error is originating from. Where do those passed in functions come from? Their resolution to an empty string is the symptom of the problem.

Why keep closing this issue while we're actively working on it, and I can reproduce it on two different setups?

**Comment by glepnir** [comment]
because  I can not reproduce. check your last comment. it seems like need a reproduce step.  check my comment today I open a test. cs it show me correct color code.

**Comment by Iron-E** [comment]
The config posted also gives me the incorrect background color. It's probably something that happens as a result of environmental conditions; since we can't get a repro on your side I'll look at this in a few days and report back.

**Comment by glepnir** [comment]
yep I still repeoduce with a min config.

**Comment by Iron-E** [comment]
I did some playing around and I think this is an issue with `nvim-devicons`, not `galaxyline`. It seems that `DevIconCs` is `:hi clear`ed every time a C# file is opened, whereas the other `DevIconXXX` groups are not (for example, running `:hi DevIconRs` displays the proper highlighting after loading a rust file). I setup a [debug branch](https://github.com/Iron-E/galaxyline.nvim/tree/debug/cs-filetype) to show what I'm talking about.

I'll ask to leave this issue open until the issue I file with `nvim-devicons` is closed.

Thanks for your patience and help so far :)

**Comment by Iron-E** [comment]
Wow! I feel like a big dummy. I looked through their source code and figured nothing could possibly be resetting the highlights, so I looked at the source code to my color scheme and saw the problem was there.

Thanks again!
