### ISSUE TITLE
Request: Add spacing field in provider function

### ISSUE THREAD

**Issue by RedBug312** [glepnir/galaxyline.nvim#89]
Trying to migrate to galaxyline these days.

For paddings between separator, like this at `section.right`
```
master | LUA | 10%
        ^   ^ these ones
```

I have to add additional spaces to separators of `FileTypeName` and `LinePercent`, or declare a function to return spaces.

```lua
local function spacing(num)
    return function() return string.rep(' ', num) end
end

gls.right[2] = {
    BufferType = {
        provider = {spacing(1), 'FileTypeName', spacing(1)},
        highlight = {c.light, c.base},
        separator = '|',
        separator_highlight = {c.light, c.base}
    }
}
```

But I think configuring it in this way would make it clear.
Or at least making the `spacing` function above built-in is fine. Thanks!

```lua
gls.right[2] = {
    BufferType = {
        provider = 'FileTypeName',
        spacing = {1, 1},  -- same to spacing = 1,
        highlight = {c.light, c.base},
        separator = '|',
        separator_highlight = {c.light, c.base}
    }
}
```

**Comment by glepnir** [comment]
Does this work `separator = ' | '` ?

**Comment by RedBug312** [comment]
Yes, but the separators requires different spaces.
`master | LUA | 10%` can be made from
```lua
gls.right[1] = {
    GitBranch = {
        provider = 'GitBranch',
        highlight = {c.light, c.base}
    }
}
gls.right[2] = {
    BufferType = {
        provider = 'FileTypeName',
        highlight = {c.light, c.base},
        separator = '| ',
        separator_highlight = {c.light, c.base}
    }
}
gls.right[3] = {
    PerCent = {
        provider = 'LinePercent',
        highlight = {c.light, c.base},
        separator = ' |',
        separator_highlight = {c.light, c.base}
    }
}
```
Do other default providers have spaces padded already?

**Comment by glepnir** [comment]
space keyword a table first index add to head. second add to tail?

**Comment by RedBug312** [comment]
Yes, I suggest that.

**Comment by glepnir** [comment]
there has a problem that number mean the space count？

**Comment by RedBug312** [comment]
Yes, the numbers of padded spaces.
Btw I found some default providers come with spaces padded already. Besides a new `spacing` column, I think stripping all the default providers and have all `separator=' | '` can be a nice workaround.

**Comment by glepnir** [comment]
right. I add some space add default provider output.so I think can close it .
