### ISSUE TITLE
Statusline not showing up

### ISSUE THREAD

**Issue by ahmedkhalf** [glepnir/galaxyline.nvim#90]
Hello, I installed the plugin and downloaded the evil line example, then sourced the lua file in my init.vim, but the statusline doesn't show up.
![image](https://user-images.githubusercontent.com/36672196/106482738-2e1f3a00-64c7-11eb-9740-06d107d75c14.png)
There are no errors on startup.

**Comment by ahmedkhalf** [comment]
Also please ignore the bad terminal, Im ssh'ing from a windows machine.

**Comment by glepnir** [comment]
`set laststauts?` output is what?

**Comment by ahmedkhalf** [comment]
The output is `last status=0`

**Comment by ahmedkhalf** [comment]
oh lol, so I set it to 2 now, and it works now, thanks for the help
