### ISSUE TITLE
Using `git root` to determine git workspace

### ISSUE THREAD

**Issue by joshuachp** [glepnir/galaxyline.nvim#92]
https://github.com/glepnir/galaxyline.nvim/blob/ee34f7fed7e2c8801a8c1a9101ab9392bc4e70a2/lua/galaxyline/provider_vcs.lua#L48

Could it be easier to refactor this function to use `git root`? I believe this method currently doesn't take in consideration a detached git-dir  and error in that case. It's already using popen to change directory so there shouldn't be any performance difference. We could use something like the following to get the root dir or check the if in a git workspace:
```lua
local cmd = io.popen('git root 2>&1')
local output = cmd:read()
cmd:close()
if output ~= "Not a git repo!" then
    print(output)
else
    print('Not git')
end
```

**Comment by glepnir** [comment]
PR Welcome.
