### ISSUE TITLE
Git diff icon doesn't show

### ISSUE THREAD

**Issue by vpeopleonatank** [glepnir/galaxyline.nvim#96]
I use [spaceline.lua](https://github.com/richin13/dotfiles/blob/develop/dotfiles/.config/nvim/lua/plugins/status-line.lua)
My statusline in modified file in git folder:
![image](https://user-images.githubusercontent.com/30976876/107202972-637ad900-6a2d-11eb-918c-5b5dcba802f4.png)

Expect:
![image](https://user-images.githubusercontent.com/30976876/107203165-a937a180-6a2d-11eb-9e07-4fb70e664792.png)

**Comment by glepnir** [comment]
hmm which git plugin do you used .

**Comment by glepnir** [comment]
nothing changed of get git diff count code.. works fine with vim-signfy

**Comment by vpeopleonatank** [comment]
> hmm which git plugin do you used .

I use `vim-fugitive`

**Comment by vpeopleonatank** [comment]
> nothing changed of get git diff count code.. works fine with vim-signfy

I 've just installed `vim-signfy`, It works. Thank you

**Comment by glepnir** [comment]
Aha. so default git diff provider only support vim-gitgutter vim-signify gitsigns. so you need write a git diff provider the n use it.
