### ISSUE TITLE
Bug with showing branch

### ISSUE THREAD

**Issue by seblj** [glepnir/galaxyline.nvim#97]
The git branch is missing if inside a folder inside a submodule.

To recreate:

Create a repository "test" and add a submodule-repository "test2" inside "test". Then create a normal folder "src" inside the submodule. The branch will not show inside the folder "src"

**Comment by glepnir** [comment]
can you show dir tree?

**Comment by seblj** [comment]
<img width="376" alt="Screenshot 2021-02-08 at 11 53 57" src="https://user-images.githubusercontent.com/5160701/107210445-6f05da00-6a04-11eb-9b02-2c07458df309.png">

Inside "src" it is not showing the branch, but it works when inside "test" and "test2". Note that "test2" is a submodule inside "test", and "src" is just a regular folder

**Comment by glepnir** [comment]
```
-- test
   -- .git
   -- test2
        -- src
           --- somefile
```
like this right?

**Comment by seblj** [comment]
Yes pretty much.

-- test
    -- .git (folder)
    -- .gitmodules
    -- test2
        -- .git (file)
        -- src
            --- somefile

**Comment by glepnir** [comment]
hmm ` -- .git (file)` what does mean? test 2 has a .git folder?

**Comment by seblj** [comment]
No it's a file which is named ```.git```. I think it's created when adding a submodule. It's only one line in it, which is: 
```gitdir: ../.git/modules/test2```

**Comment by glepnir** [comment]
so  we got gitdir = ../.git/modules/test2

**Comment by seblj** [comment]
Yes. To get the exact same setup as me, create two private repos on github named "test" and "test2". Then do this:
```
git clone git@github.com:glepnir/test.git
git submodule add git@github.com:glepnir/test2.git
cd test/test2
mkdir src
cd src
vim testfile
```
Then you will see that there is no branch showing up

**Comment by seblj** [comment]
> if you delete the .git file it will work

Ok, but is it possible to create a fix for this with the .git file there? Since it is created by default when adding a submodule

**Comment by glepnir** [comment]
should be fix by default. but I don't have today. @joshuachp can you take a look at this .PR welcome:)

**Comment by seblj** [comment]
It's ```has_git_dir``` in ```provider_vcs.lua``` which is the problem. When inside ```src``` it does not find a file or directory named ```.git```, so it goes back to ```test2```. Here it finds the ```.git``` file and returns the relative path from this folder and not the starting-folder.

**Comment by joshuachp** [comment]
Yes the relative path is the problem, writing PR with fix.

**Comment by joshuachp** [comment]
Tested locally and seams to work. Please let me know :)

I'm letting lua `io:open` work out the absolute path for the HEAD file, so we don't have to implement a function to compute the absolute directory

**Comment by joshuachp** [comment]
Sorry there was an error checking for the parent_path. Forced pushed the new changes

**Comment by seblj** [comment]
It works for me as well! Thank you!
