### ISSUE TITLE
Request: dynamic highlighting

### ISSUE THREAD

**Issue by kyoh86** [glepnir/galaxyline.nvim#99]
I want a feature which I can easily change highlight of each component dynamically.

I know that you resolved it in `example/eviline.lua`.
But I don't think that is a simple way.

IDEA:
Now, `provider` is called every time to decide a text.
So if the `highlight` contains functions, make them to be called every time to decide a color, like the `provider`.

**Comment by glepnir** [comment]
highlight key word supoort link to colorscheme highlight like highlight=String. this way is easy to config

**Comment by kyoh86** [comment]
@glepnir thanks. I'll try it.
